import type { Metadata } from "next";
import Header from "@components/layout/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className='h-full'>
      <body className='h-full'>
        <div className='max-w-5xl mx-auto p-4'>
          <Header />
        </div>
        <div className='max-w-4xl mx-auto p-4'>{children}</div>
      </body>
    </html>
  );
}
